import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {SheetsStore,HEADERS} from './sheets-store.mjs';

function fixture(){
 const rows=[[...HEADERS]],key=randomBytes(32);let timeoutAfterCommit=false,failBeforeCommit=false;
 const rangeRows=range=>{const m=range.match(/!A(\d+):([A-Z]+)(\d+)/);return rows.slice(+m[1]-1,+m[3]).map(r=>r.slice(0,m[2]==='B'?2:102));};
 const client={spreadsheets:{values:{
  get:async({range})=>({data:{values:rangeRows(range)}}),
  batchGet:async({ranges})=>({data:{valueRanges:ranges.map(range=>({values:rangeRows(range)}))}}),
  append:async(req,opts)=>{assert.equal(req.valueInputOption,'RAW');assert.equal(req.insertDataOption,'INSERT_ROWS');assert.equal(opts.retry,false);if(failBeforeCommit)throw Error('network');rows.push(...req.requestBody.values);if(timeoutAfterCommit)throw Error('timeout');return{data:{updates:{updatedRows:1}}};}
 }}};
 return{rows,store:new SheetsStore(client,'test-sheet',key),other:new SheetsStore(client,'test-sheet',key),timeout:()=>timeoutAfterCommit=true,fail:()=>failBeforeCommit=true};
}
const input=(extra={})=>({id:'mine',owner:'advisor',actor:'advisor',isNew:true,expectedVersion:0,status:'draft',payload:'encrypted assessment',engineVersion:'2.1',...extra});

test('snapshots, versions, list and encrypted index survive a fresh instance',async()=>{const f=fixture();await f.store.save(input());await f.other.save(input({isNew:false,expectedVersion:1,payload:'second snapshot'}));assert.equal(await f.other.owner('mine','advisor'),'advisor');assert.equal((await f.store.version('mine','advisor',1)).payload,'encrypted assessment');assert.equal((await f.store.list('advisor'))[0].current_version,2);assert.equal((await f.store.versions('mine','advisor'))[0].version,2);assert.ok(!f.rows[1][1].includes('advisor'));assert.equal((await f.store.list('outsider')).length,0);});
test('concurrent independent servers accept exactly one save for a version',async()=>{const f=fixture();await f.store.save(input());const results=await Promise.allSettled([f.store.save(input({isNew:false,expectedVersion:1,payload:'A'})),f.other.save(input({isNew:false,expectedVersion:1,payload:'B'}))]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.status,409);assert.equal((await f.other.versions('mine','advisor')).length,2);await assert.rejects(f.store.save(input({isNew:false,expectedVersion:1})),{status:409});});
test('access grants, contributor drafts, owner-only review and revocation',async()=>{const f=fixture();await f.store.save(input());await assert.rejects(f.store.owner('mine','insurer'),{status:404});await f.store.setAccess('mine','insurer','advisor',false);await f.other.save(input({isNew:false,expectedVersion:1,actor:'insurer'}));assert.equal((await f.store.version('mine','advisor',2)).actor,'insurer');await assert.rejects(f.other.save(input({isNew:false,expectedVersion:2,actor:'insurer',status:'reviewed'})),{status:409});await f.store.setAccess('mine','insurer','advisor',true);await assert.rejects(f.other.owner('mine','insurer'),{status:404});await assert.rejects(f.other.save(input({isNew:false,expectedVersion:2,actor:'insurer'})),{status:409});});
test('large evidence chunks round-trip and remain assessment scoped',async()=>{const f=fixture();await f.store.save(input());const payload=randomBytes(2800000).toString('base64');await f.store.addDocument({id:'doc',assessment:'mine',actor:'advisor',payload});assert.ok(f.rows[2].slice(2).every(s=>s.length<=40000));assert.equal((await f.other.document('doc','advisor')).payload,payload);assert.equal(await f.store.evidence('doc','wrong-mine'),undefined);await assert.rejects(f.other.document('doc','outsider'),{status:404});await f.store.setAccess('mine','insurer','advisor',false);assert.equal((await f.other.document('doc','insurer')).payload,payload);await f.store.setAccess('mine','insurer','advisor',true);await assert.rejects(f.other.document('doc','insurer'),{status:404});});
test('tampering with index or payload fails closed',async()=>{const f=fixture();await f.store.save(input());f.rows[1][2]='modified';await assert.rejects(f.store.version('mine','advisor',1),{status:503});f.rows[1][1]='invalid';await assert.rejects(f.store.owner('mine','advisor'));});
test('ambiguous timeout confirms exact committed event without duplicate append',async()=>{const f=fixture();f.timeout();await f.store.save(input());assert.equal(f.rows.length,2);assert.equal((await f.other.versions('mine','advisor')).length,1);});
test('failed write does not claim success',async()=>{const f=fixture();f.fail();await assert.rejects(f.store.save(input()),{status:503});assert.equal(f.rows.length,1);});
test('concurrent evidence uploads cannot exceed the 50-document limit',async()=>{const f=fixture();await f.store.save(input());for(let i=0;i<49;i++)await f.store.addDocument({id:String(i),assessment:'mine',actor:'advisor',payload:'data'});const results=await Promise.allSettled([f.store.addDocument({id:'lastA',assessment:'mine',actor:'advisor',payload:'data'}),f.other.addDocument({id:'lastB',assessment:'mine',actor:'advisor',payload:'data'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);});
test('missing headers and incomplete rows require administrator recovery',async()=>{const f=fixture();f.rows[0]=['Wrong'];await assert.rejects(f.store.read(),{status:503});f.rows[0]=HEADERS;f.rows.push([]);await assert.rejects(f.store.read(),{status:503});});
