/** Storage interface shared by the existing MySQL and interim Sheets backends. */
export const storageError=(message,status=400)=>Object.assign(new Error(message),{status});
export class MysqlStore {
 constructor(pool){this.pool=pool;}
 async owner(id,email){const [r]=await this.pool.execute('SELECT a.owner FROM workbench_assessments a WHERE a.id=? AND (a.owner=? OR EXISTS (SELECT 1 FROM workbench_access x WHERE x.assessment_id=a.id AND x.email=?))',[id,email,email]);if(!r.length)throw storageError('Assessment not found',404);return r[0].owner;}
 async access(id){const [r]=await this.pool.execute('SELECT email,granted_by,created_at FROM workbench_access WHERE assessment_id=?',[id]);return r;}
 async setAccess(id,email,actor,revoke){if(revoke)await this.pool.execute('DELETE FROM workbench_access WHERE assessment_id=? AND email=?',[id,email]);else await this.pool.execute('INSERT INTO workbench_access(assessment_id,email,granted_by) VALUES(?,?,?) ON DUPLICATE KEY UPDATE granted_by=VALUES(granted_by)',[id,email,actor]);}
 async list(email){const [r]=await this.pool.execute('SELECT a.id,a.current_version,v.status,v.payload,v.created_at FROM workbench_assessments a JOIN workbench_versions v ON v.assessment_id=a.id AND v.version=a.current_version WHERE (a.owner=? OR EXISTS (SELECT 1 FROM workbench_access x WHERE x.assessment_id=a.id AND x.email=?)) ORDER BY v.created_at DESC LIMIT 200',[email,email]);return r;}
 async save(s){const conn=await this.pool.getConnection();try{await conn.beginTransaction();if(s.isNew){if(s.expectedVersion!==0)throw storageError('New assessment version must be zero');await conn.execute('INSERT INTO workbench_assessments(id,owner,current_version) VALUES(?,?,0)',[s.id,s.owner]);}const [r]=await conn.execute('SELECT current_version FROM workbench_assessments WHERE id=? AND owner=? FOR UPDATE',[s.id,s.owner]);if(!r.length)throw storageError('Assessment not found',404);if(r[0].current_version!==s.expectedVersion)throw storageError('A newer version exists. Reopen the current assessment before saving.',409);await conn.execute('INSERT INTO workbench_versions(assessment_id,version,actor,status,payload,engine_version) VALUES(?,?,?,?,?,?)',[s.id,s.expectedVersion+1,s.actor,s.status,s.payload,s.engineVersion]);await conn.execute('UPDATE workbench_assessments SET current_version=? WHERE id=?',[s.expectedVersion+1,s.id]);await conn.commit();}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
 async versions(id,owner){const [r]=await this.pool.execute('SELECT v.version,v.actor,v.status,v.created_at AS createdAt FROM workbench_versions v JOIN workbench_assessments a ON a.id=v.assessment_id WHERE a.id=? AND a.owner=? ORDER BY v.version DESC',[id,owner]);return r;}
 async version(id,owner,v){const [r]=await this.pool.execute('SELECT v.* FROM workbench_versions v JOIN workbench_assessments a ON a.id=v.assessment_id WHERE a.id=? AND a.owner=? AND v.version=?',[id,owner,v]);if(!r.length)throw storageError('Assessment not found',404);return r[0];}
 async evidenceBatch(ids,assessment){return Promise.all(ids.map(id=>this.evidence(id,assessment)));}
 async evidence(id,assessment){const [r]=await this.pool.execute('SELECT payload FROM workbench_documents WHERE id=? AND assessment_id=?',[id,assessment]);return r[0];}
 async addDocument(d){const [r]=await this.pool.execute('SELECT COUNT(*) AS n FROM workbench_documents WHERE assessment_id=?',[d.assessment]);if(r[0].n>=50)throw storageError('Maximum 50 evidence documents per assessment');await this.pool.execute('INSERT INTO workbench_documents(id,assessment_id,owner,payload) VALUES(?,?,?,?)',[d.id,d.assessment,d.actor,d.payload]);}
 async document(id,email){const [r]=await this.pool.execute('SELECT d.payload FROM workbench_documents d JOIN workbench_assessments a ON a.id=d.assessment_id WHERE d.id=? AND (a.owner=? OR EXISTS (SELECT 1 FROM workbench_access x WHERE x.assessment_id=a.id AND x.email=?))',[id,email,email]);if(!r.length)throw storageError('Document not found',404);return r[0];}
}
